commerce_payment.commerce_payment_gateway.plugin.sbiepay_payment:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant id'
    merchant_key:
      type: string
      label: 'Merchant Key'
    currency:
      type: string
      label: 'Default Currency'
    language:
      type: string
      label: 'Language'
    pmode:
      type: string
      label: 'Mode'
