_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  administerusersbyrole: 0
  admission_customization: 0
  assign_roll_number: 0
  automated_cron: 0
  backup_migrate: 0
  barcodes: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_classes: 0
  block_content: 0
  breakpoint: 0
  change_pwd_page: 0
  ckeditor5: 0
  commerce: 0
  commerce_cart: 0
  commerce_ccavenue_mcpg: 0
  commerce_checkout: 0
  commerce_number_pattern: 0
  commerce_order: 0
  commerce_payment: 0
  commerce_price: 0
  commerce_product: 0
  commerce_store: 0
  conditional_fields: 0
  config: 0
  contextual: 0
  crop: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  email_registration: 0
  entity: 0
  entity_clone: 0
  entity_reference_revisions: 0
  entity_type_clone: 0
  examination_customization: 0
  feeds: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  field_validation: 0
  file: 0
  filefield_paths: 0
  filter: 0
  fontawesome: 0
  fontawesome_iconpicker_widget: 0
  help: 0
  history: 0
  image: 0
  image_widget_crop: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  libraries: 0
  link: 0
  markup: 0
  masquerade: 0
  menu_link_attributes: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  part_2_examination_customization: 0
  path: 0
  path_alias: 0
  phpass: 0
  phpspreadsheet: 0
  profile: 0
  redirect_after_login: 0
  registration_customization: 0
  registration_role: 0
  rest: 0
  search: 0
  serialization: 0
  shortcut: 0
  simple_block: 0
  state_machine: 0
  superfish: 0
  system: 0
  tablefield: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  ug_clc: 0
  ug_fcr: 0
  ug_miscellaneous: 0
  ug_notification: 0
  ug_payment: 0
  ug_settings: 0
  update: 0
  user: 0
  user_view_mode: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_ui: 0
  yearonly: 0
  hide_revision_field: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  olivero: 0
  claro: 0
  bootstrap5: 0
  allinonecms: 0
  stable9: 0
profile: standard
