cloneable_entities:
  - commerce_order_item
  - commerce_order_item_type
  - commerce_order_type
  - commerce_payment
  - commerce_payment_gateway
  - commerce_payment_method
  - commerce_currency
  - commerce_product
  - commerce_product_attribute
  - commerce_product_attribute_value
  - commerce_product_type
  - commerce_product_variation
  - commerce_product_variation_type
  - commerce_store
  - commerce_store_type
  - crop
  - crop_type
  - editor
  - feeds_feed
  - feeds_feed_type
  - feeds_subscription
  - field_config
  - field_storage_config
  - file
  - filter_format
  - image_style
  - menu_link_content
  - node
  - node_type
  - path_alias
  - profile
  - profile_type
  - rest_resource_config
  - search_page
  - shortcut
  - shortcut_set
  - simple_block
  - action
  - menu
  - taxonomy_term
  - taxonomy_vocabulary
  - tour
  - user_role
  - user
  - pathauto_pattern
  - view
  - date_format
  - entity_form_display
  - entity_form_mode
  - entity_view_display
  - entity_view_mode
  - base_field_override
  - field_validation_rule_set
