commerce_payment.commerce_payment_gateway.plugin.ccavenue_payment:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant id'
    access_code:
      type: string
      label: 'CCavenue Access Code'
    working_key:
      type: string
      label: 'CCavenue Working Key'
    merchant_id2:
      type: string
      label: 'Merchant id2'
    access_code2:
      type: string
      label: 'CCavenue Access Code2'
    working_key2:
      type: string
      label: 'CCavenue Working Key2'
    currency:
      type: string
      label: 'Default Currency'
    language:
      type: string
      label: 'Language'
    pmode:
      type: string
      label: 'Mode'
